### Pandas
Pandas is a powerful data manipulation library in Python, widely used for data analysis  and data cleaning.

In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
### Series -- it is a one dimensional array like object that can hold any type data.

data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n", series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
 ### Create a Series from dictonary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.Series'>

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
### Data frame-

## create a Dataframe from a dictonary of list

data={
    'Name':['Jack','John','Arther'],
    'Age':[21,25,35],
    'City':['LA','Paris','Lucknow']
}

df=pd.DataFrame(data)
print(df)

     Name  Age     City
0    Jack   21       LA
1    John   25    Paris
2  Arther   35  Lucknow

In [7]:
print(df)

     Name  Age     City
0    Jack   21       LA
1    John   25    Paris
2  Arther   35  Lucknow

In [8]:
import numpy as np
np.array(df)

array([['Jack', 21, 'LA'],
       ['John', 25, 'Paris'],
       ['Arther', 35, 'Lucknow']], dtype=object)

In [16]:
### Create a Data frame from a list of Dictonaries
data=[
    {'Name':'Jack','age':21,'City':'Lucknow'},
     {'Name':'John','age':21,'City':'Hardoi'},
      {'Name':'Jaugar','age':21,'City':'Mallawan'},
       {'Name':'Joker','age':21,'City':'Bilgram'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  age      City
0    Jack   21   Lucknow
1    John   21    Hardoi
2  Jaugar   21  Mallawan
3   Joker   21   Bilgram
<class 'pandas.DataFrame'>

In [17]:
### Accessing a specified element

df.at[2,'age']

np.int64(21)

In [19]:
df.iat[2,2]

'Mallawan'

In [20]:
df

     Name  age      City
0    Jack   21   Lucknow
1    John   21    Hardoi
2  Jaugar   21  Mallawan
3   Joker   21   Bilgram

In [21]:
## Data Manulpulation with dataframe
df['Salary']=[50000,60000,70000,80000]
df

     Name  age      City  Salary
0    Jack   21   Lucknow   50000
1    John   21    Hardoi   60000
2  Jaugar   21  Mallawan   70000
3   Joker   21   Bilgram   80000

In [24]:
### Remove  a column
df.drop('Salary',axis=1,inplace=True)

In [25]:
df

     Name  age      City
0    Jack   21   Lucknow
1    John   21    Hardoi
2  Jaugar   21  Mallawan
3   Joker   21   Bilgram

In [27]:
###Add age to the column

df['age']=df['age']+1

In [28]:
df

     Name  age      City
0    Jack   22   Lucknow
1    John   22    Hardoi
2  Jaugar   22  Mallawan
3   Joker   22   Bilgram

In [29]:
df.describe()

        age
count   4.0
mean   22.0
std     0.0
min    22.0
25%    22.0
50%    22.0
75%    22.0
max    22.0