In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
## Create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
##  Create an instance of Onehotencoder
encoder=OneHotEncoder()

In [7]:
###Perform fit anf transform

encoded=encoder.fit_transform(df[['color']]).toarray()

In [8]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [9]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [10]:
encoder.transform([['blue']]).toarray()

c:\Users\vikra\OneDrive\Pictures\Desktop\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [11]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [17]:
import seaborn as sns
df1=sns.load_dataset('tips')
df1.head()
df1['sex'].unique()

['Female', 'Male']
Categories (2, str): ['Male', 'Female']

In [20]:
encode_df=encoder.fit_transform(df1[['sex']]).toarray()

In [24]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

ValueError: Shape of passed values is (6, 3), indices imply (6, 2)